import json
from pathlib import Path
T = Path(__file__).resolve().parent.parent
SPEC = {'theme': 'he_bold',
 'palette': {'acc': '#E63B2E', 'ink': '#111111', 'lt': '#F5F3EE', 'panel': 'rgba(14,14,14,.74)', 'sub': '#E4E1DB'},
 'music_vol': 0.6,
 'plate_vol': 0.35,
 'css': '\n'
        '/* adkit flash fromTo renders .3 white from t=0 until the first stomp -> milky plate */\n'
        '#flash{display:none}\n'
        '/* single accent: soft depth shadow instead of a hard offset */\n'
        '.st span.c{text-shadow:0 18px 70px rgba(0,0,0,.55)!important}\n'
        '.st i.he{color:var(--lt);text-shadow:0 0 14px rgba(0,0,0,.95),0 0 36px rgba(0,0,0,.8),0 2px 4px rgba(0,0,0,.9)}\n'
        '.co{width:360px;box-sizing:border-box;text-align:right}\n'
        '.co .a{font-size:34px}\n'
        '.co .b{font-size:21px;color:var(--sub)}\n'
        '.co .b em{font-style:normal;font-weight:700;color:var(--acc)}\n'
        '#e8,#e11{margin-left:70px}\n'
        '#chip .a{font-size:36px}\n'
        '.ct{direction:rtl;text-align:right;min-width:250px}\n'
        '.ct .v{direction:ltr;text-align:right;letter-spacing:0}\n'
        '.ct .u{font-family:"Assistant",sans-serif;font-weight:600;font-size:24px;letter-spacing:0;direction:rtl;width:auto}\n'
        '.rg svg{opacity:.8}\n'
        '/* callout exit: leader line, dot and pulse ring fade with the glass box */\n'
        '#e8L,#e9L,#e10L,#e11L{animation:coOutS .12s linear 9.28s 1 both}\n'
        '#e8D,#e9D,#e10D,#e11D{animation:coOutFS .12s linear 9.28s 1 both}\n'
        '#e8R,#e9R,#e10R,#e11R{animation:coOutS .12s linear 9.28s 1 both}\n'
        '@keyframes coOutS{from{stroke-opacity:1}to{stroke-opacity:0}}\n'
        '@keyframes coOutFS{from{stroke-opacity:1;fill-opacity:1}to{stroke-opacity:0;fill-opacity:0}}\n'
        '#lock .a{font-size:64px}\n'
        '#lock .b{font-family:"Assistant",sans-serif;font-weight:300;font-size:48px;color:var(--lt)}\n',
 'elements': [{'type': 'ring', 'obj': 'shoe', 'r': 440, 'spin': 0.6, 't': 0.25, 'end': 4.5},
              {'type': 'kine',
               'x': 960,
               'y': 105,
               't': 0.4,
               'end': 2.02,
               'exit': 'up',
               'lines': [[{'w': 'קלה', 't': 0.4, 'size': 140}, {'w': 'כמו', 't': 0.609, 'size': 140, 'style': 'outline'}]]},
              {'type': 'kine',
               'behind': True,
               'x': 960,
               'y': 880,
               't': 0.98,
               'end': 2.02,
               'exit': 'down',
               'lines': [[{'w': 'אוויר', 't': 0.98, 'size': 380, 'style': 'accent', 'font': 'big', 'hit': True}]]},
              {'type': 'kine',
               'x': 960,
               'y': 215,
               't': 2.1,
               'end': 4.55,
               'exit': 'up',
               'lines': [[{'w': 'ארבע', 't': 2.1, 'size': 190}, {'w': 'שכבות', 't': 2.704, 'size': 190, 'style': 'accent', 'hit': True}],
                         [{'w': 'אפס', 't': 3.354, 'size': 150}, {'w': 'פשרות', 't': 3.656, 'size': 150, 'hit': True, 'amt': 0.5}]]},
              {'type': 'chip', 'text': 'מבט פנימה', 'sub': 'GUYAGA AERO · מבנה', 't': 4.6, 'end': 9.4},
              {'type': 'ring', 'obj': 'a_plate', 'r': 70, 'spin': 1.4, 't': 7.3, 'end': 9.4},
              {'type': 'ring', 'obj': 'a_mid', 'r': 55, 'spin': -1.2, 't': 6.1, 'end': 9.4},
              {'type': 'callout',
               'obj': 'a_upper',
               'fx': 0.5,
               'fy': 0.5,
               'title': 'עליון סרוג',
               'sub': 'נושם בכל צעד · <em>38 גרם</em>',
               'x': -10,
               'y': 200,
               't': 4.95,
               'end': 9.4},
              {'type': 'callout',
               'obj': 'a_mid',
               'fx': 0.5,
               'fy': 0.5,
               'title': 'קצף תגובתי',
               'sub': 'החזר אנרגיה 87% · <em>86 גרם</em>',
               'x': 1520,
               'y': 400,
               't': 6.1,
               'end': 9.4},
              {'type': 'callout',
               'obj': 'a_plate',
               'fx': 0.5,
               'fy': 0.5,
               'title': 'לוח קרבון',
               'sub': '0.9 מ״מ, לכל האורך · <em>17 גרם</em>',
               'x': 1520,
               'y': 640,
               't': 7.3,
               'end': 9.4},
              {'type': 'callout',
               'obj': 'a_out',
               'fx': 0.5,
               'fy': 0.5,
               'title': 'סוליית אחיזה',
               'sub': 'אחיזה גם ברטוב · <em>48 גרם</em>',
               'x': -10,
               'y': 800,
               't': 8.3,
               'end': 9.4},
              {'type': 'kine',
               'behind': False,
               'x': 960,
               'y': 300,
               't': 10.25,
               'end': 12.28,
               'exit': 'down',
               'lines': [[{'w': 'והכול', 't': 10.25, 'size': 130, 'style': 'outline'}],
                         [{'w': 'מתחבר', 't': 10.97, 'size': 330, 'style': 'accent', 'font': 'big', 'hit': True}]]},
              {'type': 'counter',
               't0': 9.95,
               't1': 11.0,
               'a': 0,
               'b': 189,
               'label': 'גרם · משקל הנעל',
               'x': 70,
               'y': 300,
               'size': 120,
               't': 9.95,
               'end': 12.35},
              {'type': 'counter',
               't0': 10.2,
               't1': 11.2,
               'a': 0,
               'b': 87,
               'suf': '%',
               'label': 'החזר אנרגיה',
               'x': 70,
               'y': 560,
               'size': 120,
               't': 10.2,
               'end': 12.35},
              {'type': 'counter',
               't0': 10.45,
               't1': 11.4,
               'a': 0,
               'b': 8,
               'label': 'מ״מ · דרופ',
               'x': 1590,
               'y': 300,
               'size': 120,
               't': 10.45,
               'end': 12.35},
              {'type': 'counter',
               't0': 10.7,
               't1': 11.6,
               'a': 0,
               'b': 0.9,
               'dec': 1,
               'label': 'מ״מ · לוח קרבון',
               'x': 1590,
               'y': 560,
               'size': 120,
               't': 10.7,
               'end': 12.35},
              {'type': 'kine',
               'behind': False,
               'x': 960,
               'y': 330,
               't': 12.3,
               'end': 13.72,
               'exit': 'up',
               'lines': [[{'w': 'GUYAGA', 't': 12.3, 'size': 260, 'font': 'big'}],
                         [{'w': 'AERO', 't': 13.14, 'size': 470, 'style': 'accent', 'font': 'big', 'hit': True}]]},
              {'type': 'lockup', 'brand': 'GUYAGA AERO', 't': 13.75},
              {'type': 'kine',
               'x': 960,
               'y': 250,
               't': 13.75,
               'lines': [[{'w': 'רצים', 't': 13.75, 'size': 180},
                          {'w': 'על', 't': 14.214, 'size': 140, 'style': 'outline'},
                          {'w': 'אוויר', 't': 14.423, 'size': 200, 'style': 'accent', 'hit': True}]]},
              {'type': 'punch', 'times': [0.98, 2.704, 3.656, 10.97, 13.14, 14.423], 'amt': 1.1},
              {'type': 'flash', 'text': 'אוויר!', 't': 1.26, 'dur': 0.16, 'size': 560},
              {'type': 'flash', 'text': 'AERO!', 't': 13.42, 'dur': 0.16, 'size': 600, 'bg': '#111111', 'color': 'var(--acc)'},
              {'type': 'captions',
               'words': [{'w': 'קלה', 't': 0.4},
                         {'w': 'כמו', 't': 0.609},
                         {'w': 'אוויר.', 't': 0.98},
                         {'w': 'ארבע', 't': 2.1},
                         {'w': 'שכבות.', 't': 2.704},
                         {'w': 'אפס', 't': 3.354},
                         {'w': 'פשרות.', 't': 3.656},
                         {'w': 'עליון', 't': 4.9},
                         {'w': 'נושם.', 't': 5.388},
                         {'w': 'קצף', 't': 6.1},
                         {'w': 'תגובתי.', 't': 6.472},
                         {'w': 'לוח', 't': 7.3},
                         {'w': 'קרבון.', 't': 7.532},
                         {'w': 'אחיזה', 't': 8.25},
                         {'w': 'בכל', 't': 8.923},
                         {'w': 'תנאי.', 't': 9.643},
                         {'w': 'והכול', 't': 10.25},
                         {'w': 'מתחבר.', 't': 10.97},
                         {'w': 'גאיאגה', 't': 12.3},
                         {'w': 'אירו.', 't': 13.136},
                         {'w': 'רצים', 't': 13.75},
                         {'w': 'על', 't': 14.214},
                         {'w': 'אוויר.', 't': 14.423}],
               'max': 3,
               't': 0.4,
               'end': 15.0}],
 'vo_name': 'E6_sneaker_he_vo'}
